const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.Persist,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.EightDir,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.Bullet.Acts.SetSpeed
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{GroundStage1: 0},
	{Item: 0},
	{HP: 0},
	{GunSlot: 0},
	{CanShot: 0},
	{CanAttack: 0},
	{CanThrowBomb: 0},
	{IsDamage: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Character: 0},
	{InvisibleWall: 0},
	{Sine: 0},
	{DoorStage1: 0},
	{GroundStage2: 0},
	{Death: 0},
	{HPBar: 0},
	{YellowCubeHP: 0},
	{Sine2: 0},
	{Enemy: 0},
	{BulletLife: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Keyboard: 0},
	{Persist: 0},
	{Silver: 0},
	{Gold: 0},
	{Diamond: 0},
	{TextCash: 0},
	{CashIcon: 0},
	{GroundShop1: 0},
	{DoorShop1: 0},
	{Price: 0},
	{Shop1Item1: 0},
	{Shop1Item2: 0},
	{Shop1Item3: 0},
	{TextShop1PriceItem1: 0},
	{TextShop1PriceItem2: 0},
	{TextShop1PriceItem3: 0},
	{TextSlotBullet: 0},
	{LabelSlot: 0},
	{RechargeBullet: 0},
	{ItemShotgun: 0},
	{BulletShotgun01: 0},
	{BulletShotgun02: 0},
	{BulletShotgun03: 0},
	{Mouse: 0},
	{Pin: 0},
	{Attack: 0},
	{Grenade: 0},
	{Fade: 0},
	{Explosion: 0},
	{GrenadeBar: 0},
	{ItemBow: 0},
	{Arrow: 0},
	{HPStroke: 0},
	{FireBar: 0},
	{Particles: 0},
	{DoorStage2: 0},
	{GroundBoss: 0},
	{State: 0},
	{"8Direction": 0},
	{Boss: 0},
	{Miniboss: 0},
	{Enemy2: 0},
	{FireHitbox: 0},
	{BossPosition: 0},
	{Cash: 0},
	{Guns: 0},
	{Fire: 0},
	{SlotBullet: 0},
	{GrenadeCharge: 0},
	{Items: 0}
];

self.InstanceType = {
	GroundStage1: class extends self.ISpriteInstance {},
	Character: class extends self.ISpriteInstance {},
	InvisibleWall: class extends self.ISpriteInstance {},
	Item: class extends self.ISpriteInstance {},
	DoorStage1: class extends self.ISpriteInstance {},
	GroundStage2: class extends self.ISpriteInstance {},
	Death: class extends self.ISpriteInstance {},
	HPBar: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Silver: class extends self.ISpriteInstance {},
	Gold: class extends self.ISpriteInstance {},
	Diamond: class extends self.ISpriteInstance {},
	TextCash: class extends self.ITextInstance {},
	CashIcon: class extends self.ISpriteInstance {},
	GroundShop1: class extends self.ISpriteInstance {},
	DoorShop1: class extends self.ISpriteInstance {},
	Shop1Item1: class extends self.ISpriteInstance {},
	Shop1Item2: class extends self.ISpriteInstance {},
	Shop1Item3: class extends self.ISpriteInstance {},
	TextShop1PriceItem1: class extends self.ITextInstance {},
	TextShop1PriceItem2: class extends self.ITextInstance {},
	TextShop1PriceItem3: class extends self.ITextInstance {},
	TextSlotBullet: class extends self.ITextInstance {},
	LabelSlot: class extends self.ISpriteInstance {},
	RechargeBullet: class extends self.ISpriteInstance {},
	ItemShotgun: class extends self.ISpriteInstance {},
	BulletShotgun01: class extends self.ISpriteInstance {},
	BulletShotgun02: class extends self.ISpriteInstance {},
	BulletShotgun03: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Attack: class extends self.ISpriteInstance {},
	Grenade: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	GrenadeBar: class extends self.ISpriteInstance {},
	ItemBow: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	HPStroke: class extends self.ISpriteInstance {},
	FireBar: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	DoorStage2: class extends self.ISpriteInstance {},
	GroundBoss: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	Miniboss: class extends self.ISpriteInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	FireHitbox: class extends self.ISpriteInstance {},
	BossPosition: class extends self.ISpriteInstance {},
	Cash: class extends self.ISpriteInstance {},
	Guns: class extends self.ISpriteInstance {}
}